name: Update

on:
  schedule:
    - cron: '0 * * * *'
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install RPM tools
        run: sudo apt-get install -y rpm

      - name: Get `aosc-findupdate`
        run: git clone https://github.com/Suyun114/openRuyi-findupdate

      - name: Get `openRuyi`
        run: git clone https://github.com/openRuyi-Project/openRuyi.git

      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            openRuyi-findupdate/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build `aosc-findupdate`
        run: |
          cd openRuyi-findupdate
          cargo build --release

      - name: Generate `pkgsupdate.json`
        run: ./openRuyi-findupdate/target/release/aosc-findupdate --dry-run -t ./openRuyi-findupdate/chkupdates.toml -d ./openRuyi -j "$PWD"/pkgsupdate.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate `anicca-data.json`
        run: python ./scripts/convert-data.py -o anicca-data.json

      - name: Render markdown
        run: cat pkgsupdate.json | python ./scripts/render-markdown.py > README.md

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
